src/Models/Phonebook/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

public class Contact
{
    public int ID { get; set; }

    public string User { get; set; }

    public string firstName { get; set; }

    public string lastName { get; set; }

    public string address { get; set; }

    public string city { get; set; }

    public string State { get; set; }
    public int zip { get; set; }

    //public List<Phone> Numbers { get; set; }

}

src/Models/Phonebook/PhoneNumber.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

public class PhoneNumber 
{
    public int? ID { get; set; }
    public string number { get; set; }
}

src/Models/Phonebook/SqlModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;

public class SqlModel
{
    public string dataSource { get; set; }
    public string initialCatalog { get; set; }
    public string userID { get; set; }
    public string password { get; set; }

    public string currentEmail { get; set; }
    public string sampleString { get; set; }

    public SqlModel(string datasource, string initialcatalog, string userid, string password, string currentUser)
    {
        this.dataSource = datasource;
        this.initialCatalog = initialcatalog;
        this.userID = userid;
        this.password = password;
        this.currentEmail = currentUser;
    }

    public SqlConnectionStringBuilder BuildConnectionString()
    {
        SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder()
        {
            DataSource = this.dataSource,
            InitialCatalog = this.initialCatalog,
            UserID = this.userID,
            Password = this.password
        };

        return builder;
    }
    //DataSource=;InitialCatalog=;UserID=;Password=;

    public void CreateContact(Contact contact, string user)
    {
        var builder = BuildConnectionString();

        string connectionString = builder.ConnectionString;



        using (SqlConnection conn = new SqlConnection(connectionString))
        {

            conn.Open();

            using (SqlCommand cmd = new SqlCommand("dbo.CreateContact", conn))
            {
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@EMAIL", user);
                cmd.Parameters.AddWithValue("@FIRSTNAME", contact.firstName);
                cmd.Parameters.AddWithValue("@LASTNAME", contact.lastName);
                cmd.Parameters.AddWithValue("@ADDRESS", contact.address);
                cmd.Parameters.AddWithValue("@CITY", contact.city);
                cmd.Parameters.AddWithValue("@STATE", contact.State);
                cmd.Parameters.AddWithValue("@ZIP", contact.zip);


                cmd.ExecuteNonQuery();
            }

        }
    }

    public void AddPhoneNumber(int ID, string number)
    {
        var builder = BuildConnectionString();

        using (SqlConnection conn = new SqlConnection(builder.ConnectionString))
        {
            conn.Open();

            using (SqlCommand cmd = new SqlCommand("dbo.AddPhone", conn))
            {
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@ID", ID);
                cmd.Parameters.AddWithValue("@NUMBER", number);

                cmd.ExecuteNonQuery();

            }
        }
    }

    public void DeleteContact(int id)
    {
        var builder = BuildConnectionString();

        string connectionString = builder.ConnectionString;

        using (SqlConnection conn = new SqlConnection(connectionString))
        {
            conn.Open();

            using (SqlCommand cmd = new SqlCommand("dbo.DeleteContact", conn))
            {
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@ID", id);

                cmd.ExecuteNonQuery();
            }
        }
    }
    public void DeleteNumber(string number) 
    {
        var builder = BuildConnectionString();

        string connectionString = builder.ConnectionString;

        using (SqlConnection conn = new SqlConnection(connectionString))
        {
            conn.Open();

            using (SqlCommand cmd = new SqlCommand("dbo.DeleteNumber", conn))
            {
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@NUMBER", number);

                cmd.ExecuteNonQuery();
            }
        }
    }


    public void EditContact(Contact contact, int ID)
    {

        var builder = BuildConnectionString();

        using (SqlConnection conn = new SqlConnection(builder.ConnectionString))
        {

            conn.Open();

            using (SqlCommand cmd = new SqlCommand("dbo.UpdateContact", conn))
            {

                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@ID", ID);
                cmd.Parameters.AddWithValue("@FIRSTNAME", contact.firstName);
                cmd.Parameters.AddWithValue("@LASTNAME", contact.lastName);
                cmd.Parameters.AddWithValue("@ADDRESS", contact.address);
                cmd.Parameters.AddWithValue("@CITY", contact.city);
                cmd.Parameters.AddWithValue("@STATE", contact.State);
                cmd.Parameters.AddWithValue("@ZIP", contact.zip);

                cmd.ExecuteNonQuery();
            }
        }

    }


    public List<Contact> GetContacts()
    {
        List<Contact> contacts = new List<Contact>();

        var builder = BuildConnectionString();

        using (SqlConnection conn = new SqlConnection(builder.ConnectionString))
        {
            conn.Open();
            using (SqlCommand cmd = new SqlCommand($"SELECT * FROM CONTACTS WHERE EMAIL = '{this.currentEmail}'", conn))
            {
                var reader = cmd.ExecuteReader();

                while (reader.Read())
                {
                    var temp = new Contact
                    {

                        ID = Convert.ToInt32(reader["ID"].ToString()),
                        User = (string)reader["Email"].ToString(),
                        firstName = (string)reader["FirstName"].ToString(),
                        lastName = (string)reader["LastName"].ToString(),
                        address = (string)reader["Address"].ToString(),
                        city = (string)reader["City"].ToString(),
                        State = (string)reader["State"].ToString(),
                        zip = Convert.ToInt32(reader["Zip"].ToString())

                    };


                    contacts.Add(temp);
                }
            }
        }

        return contacts;
    }

    public Contact GetContact(int ID)
    {
        Contact retrievedContact = null;

        var builder = BuildConnectionString();

        using (SqlConnection conn = new SqlConnection(builder.ConnectionString))
        {
            conn.Open();

            using (SqlCommand cmd = new SqlCommand("dbo.GetContact", conn))
            {
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@ID", ID);

                var reader = cmd.ExecuteReader();
                while (reader.Read())
                {
                    retrievedContact = new Contact()
                    {
                        ID = Convert.ToInt32(reader["ID"].ToString()),
                        User = (string)reader["Email"].ToString(),
                        firstName = (string)reader["FirstName"].ToString(),
                        lastName = (string)reader["LastName"].ToString(),
                        address = (string)reader["Address"].ToString(),
                        city = (string)reader["City"].ToString(),
                        State = (string)reader["State"].ToString(),
                        zip = Convert.ToInt32(reader["Zip"].ToString())
                    };
                }

            }
        }

        return retrievedContact;
    }

    
    public List<PhoneNumber> GetPhoneNumbers(int ID) 
    {
        List<PhoneNumber> numbers = new List<PhoneNumber>();

        var builder = BuildConnectionString();

        using (SqlConnection conn = new SqlConnection(builder.ConnectionString))
        {
            conn.Open();

            using (SqlCommand cmd = new SqlCommand("dbo.GetNumbers", conn))
            {
                cmd.CommandType = System.Data.CommandType.StoredProcedure;

                cmd.Parameters.AddWithValue("@ID", ID);

                var reader = cmd.ExecuteReader();
                while (reader.Read()) 
                {
                    PhoneNumber temp = new PhoneNumber() 
                    {
                        number = reader["number"].ToString()
                    };

                    numbers.Add(temp);
                }
            }
        }
        return numbers;
    }


}

src/Controllers/PhoneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhonebookwithAuth.Controllers
{
    public class PhoneController : Controller
    {


        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Createe(string F, string L, string A, string C, string S, string Z, string P)
        {
            Contact contact = new Contact()
            {
                firstName = F,
                lastName = L,
                address = A,
                city = C,
                State = S,
                zip = Convert.ToInt32(Z)
            };

            SqlModel sql = new SqlModel("", User.Identity.Name);

            sql.CreateContact(contact, User.Identity.Name);
            System.Diagnostics.Debug.WriteLine(" This is working!");
            return RedirectToAction("PhonebookView");

        }

        [Authorize]
        [HttpGet]
        public ActionResult AddNumber(int ID, string F)
        {
            ViewBag.PassedID = ID;
            ViewBag.Name = F;

            return View("AddNumberView");
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddNumber(string P, int ID, string Name) 
        {
            SqlModel sql = new SqlModel("", User.Identity.Name);

            sql.AddPhoneNumber(ID, P);


            var nextView = View(NumbersView(ID, Name));

            return RedirectToAction("NumbersView", new {ID = ID, firstName = Name });
        }

        public ActionResult DeleteContact(int ID)
        {

            SqlModel sql = new SqlModel("", User.Identity.Name);

            sql.DeleteContact(ID);
            System.Diagnostics.Debug.WriteLine($"Contact with ID: {ID}, Deleted");
            return RedirectToAction("PhonebookView");
        }

        public ActionResult DeleteNumber(string num, string F, string ID) 
        {
            SqlModel sql = new SqlModel("", User.Identity.Name);

            sql.DeleteNumber(num);
            return RedirectToAction("NumbersView", new { ID = ID, firstName = F });
        }


        [Authorize]
        [HttpGet]
        public ActionResult EditContact(int ID) 
        {
            SqlModel sql = new SqlModel("", User.Identity.Name);

            Contact currentContact = sql.GetContact(ID);

            ViewBag.First = currentContact.firstName;
            ViewBag.Last = currentContact.lastName;
            ViewBag.Address = currentContact.address;
            ViewBag.City = currentContact.city;
            ViewBag.State = currentContact.State;
            ViewBag.Zip = currentContact.zip;
            ViewBag.ID = ID;

            return View("Edit");
        }
        
        [HttpPost]
        public ActionResult EditContactt(string F, string L, string A, string C, string S, int Z, int ID) 
        {
            SqlModel sql = new SqlModel("", User.Identity.Name);

            Contact updatedContact = new Contact()
            {
                firstName = F,
                lastName = L,
                address = A,
                city = C,
                State = S,
                zip = Z
            };
            

            sql.EditContact(updatedContact, ID);


            return RedirectToAction("PhonebookView");
        }



        //add alternate details view to view actual numbers
        //Make alternate search view for phonebook 
        //make a post for this so itll return another view with search table
        [Authorize]
        public ActionResult PhonebookView(string search)
        {

            ViewBag.Userr = User.Identity.Name;

            SqlModel sql = new SqlModel("", User.Identity.Name);

            IEnumerable<Contact> model = sql.GetContacts();

            //temp return value
            return View("PhonebookView", model);
        }

        [Authorize]
        public ActionResult NumbersView(int ID, string firstName) 
        {
            ViewBag.ID = ID;
            ViewBag.First = firstName;

            SqlModel model = new SqlModel("", User.Identity.Name);
            
            return View(model);
        }

        public ActionResult _partialGrid(string search) 
        {
            ViewBag.Userr = User.Identity.Name;

            SqlModel sql = new SqlModel("", User.Identity.Name);

            IEnumerable<Contact> model = sql.GetContacts();

            if (!String.IsNullOrWhiteSpace(search))
            {
                model = model.Where(s => s.firstName.Contains(search)).ToList();
            }

            return PartialView(model);
        }
    }

}

src/Views/Phone/AddNumberView.cshtml

@{
    ViewBag.Title = "AddNumberView";
}

<h2>AddNumberView</h2>
@using (Html.BeginForm())
{
<div class="text-center" style="justify-content:center">

    <p>Phone Number:</p>
    <input placeholder="Number" name="P" />
    <input type="text" name="ID" value="@ViewBag.PassedID" style="display:none;" />
    <input type="text" name="Name" value="@ViewBag.Name" style="display:none;" />
    <input type="submit" />

</div>
}

src/Views/Phone/Create.cshtml
@model Contact

@{
    ViewBag.Title = "Create";
}

<h2 class="bg-info" style="margin-bottom:0px;background-color: whitesmoke;">Create new contact..</h2>
<div class="bg-info text-center" style="padding-top:10px;background-color: whitesmoke;">

    @using (Html.BeginForm("Createe", "Phone"))
    {
        <p>First Name:</p>
        <input type="text" name="F" />

        <p>Last Name:</p>
        <input type="text" name="L" />

        <p>Address:</p>
        <input type="text" name="A" />

        <p>City:</p>
        <input type="text" name="C" />

        <p>State:</p>
        <input type="text" name="S" />

        <p>Zip:</p>
        <input type="text" name="Z" />

        <br />

        <input type="submit" name="CreateContact" />
    }

</div>

<div class="jumbotron text-center" style="">
    <h1>You can add phone numbers through the Details page after initial contact creation</h1>
</div>

src/Views/Phone/Edit.cshtml

@{
    ViewBag.Title = "Edit";
    ViewBag.ID = ViewBag.ID;
}


<h2 class="bg-info" style="margin-bottom:0px;background-color: whitesmoke;">Edit...</h2>
<div class="bg-info text-center" style="padding-top:10px;background-color: whitesmoke;">

    @using (Html.BeginForm("EditContactt", "Phone"))
    {
        <p>First Name:</p>
        <input type="text" value="@ViewBag.First" name="F" />

        <p>Last Name:</p>
        <input type="text" value="@ViewBag.Last" name="L" />

        <p>Address:</p>
        <input type="text" value="@ViewBag.Address" name="A"/>

        <p>City:</p>
        <input type="text" value="@ViewBag.City" name="C"/>

        <p>State:</p>
        <input type="text" value="@ViewBag.State" name="S"/>

        <p>Zip:</p>
        <input type="text" value="@ViewBag.Zip" name="Z"/>
        <!--just doing this to pass ID back to Post Action-->
        <input value="@ViewBag.ID" name="ID" style="display:none"/>
        <br />
        <p>Phone Number Coming Soon...</p>

        <input type="submit" name="EditContact" />
    }

</div>

src/Views/Phone/NumbersView.cshtml
@model SqlModel
@{
    ViewBag.Title = "NumbersView";
    WebGrid grid = new WebGrid(Model.GetPhoneNumbers(ViewBag.ID));
}
<style>
    .webGrid {
        width: 100%;
        padding: 10px;
        margin:10px;
        background-color: ghostwhite;
    }

    .rows {
        background-color: whitesmoke;
    }

    .header {
        background-color: darkgray;
        text-align: right;
        justify-content: center;
    }

    .select {
        background-color: grey;
    }
</style>
<!--Numbers and number creation/deletion basically same screen as phonebookview-->

<div class="jumbotron">
    <table>
        <tr>
            <th><h2>Numbers for @ViewBag.First</h2></th>
            <th></th>
        </tr>
        <div style="text-align:center; justify-content:center;">
            <button class="btn-lg btn-success text-center" style="text-align:center; justify-content:center">@Html.ActionLink("Add Number", "AddNumber", "Phone", new { ID = ViewBag.ID, F = ViewBag.First }, null)</button>
        </div>
@grid.GetHtml(tableStyle: "webGrid", headerStyle: "header", selectedRowStyle:
 "select", rowStyle: "rows", fillEmptyRows: true, columns: grid.Columns(
     grid.Column("number", "Phone Numbers"),
grid.Column(header: "Actions", format:
                            @<text>
                                <button class="btn btn-danger">@Html.ActionLink("Delete", "DeleteNumber", "Phone", new { num = item.number, F = ViewBag.First, ID = ViewBag.ID }, null)</button>
                            </text>)))


    </table>
</div>

src/Views/Phone/PhonebookView.cshtml
@model IEnumerable<Contact>
@{
    ViewBag.Title = "PhonebookView";
    WebGrid newGrid = new WebGrid(Model, rowsPerPage: 15);
    
    
}
    <style>
        .webGrid 
        {
            width: 100%;
            padding:10px;
            background-color: ghostwhite;
            
        }
        .rows 
        {
            background-color: whitesmoke;
        }
        .header 
        {
            background-color: darkgray;
        }

        .select 
        {
            background-color: grey;
        }


    </style>
    <div style="background-color:whitesmoke;margin-top: 0px; width: 100%;">

        <h1 style="margin-top:5px;text-align: center; justify-content:center">Hello, @ViewBag.Userr</h1>

        <div class="row">

            <div class="col-lg-12 col-sm-12 col-md-12 text-center">
                <div class="btn-group-lg text-center" style="justify-content:center;text-align: center;">
                    <button class="btn-lg btn-success">@Html.ActionLink("Create Contact","Create","Phone")</button>
                </div>
            </div>

        </div>

        <div style="margin:25px">

            <h2>My Phone Numbers:</h2>


            <input id="livesearchtags" name="livesearchtags"  placeholder="Search" />
            <div id="result" class="tag-results">

                <!--maybe make bool for search vs non search table?-->
                <!--This does not work very well-->
                @Html.Partial("_partialGrid")


            </div>
        </div>
<script>


    document.getElementById('livesearchtags').addEventListener('keyup', function (e)
    {
        //Run LiveSearch on every key up 
        LiveSearch()
    });

    function LiveSearch()
    {
        //Get the input value
        let value = document.getElementById('livesearchtags').value

        $.ajax
            ({
            type: "POST",
            url: "/Phone/_partialGrid",
            // Attach the value to a parameter called search
            data: { search: value },
            datatype: "html",
            success: function (data) {
                $('#result').html(data);
            }
        });
    }
</script>

src/Views/Phone/_partialGrid.cshtml
@model IEnumerable<Contact>
@{
    ViewBag.Title = "_partialGrid";
    WebGrid newGrid = new WebGrid(Model, rowsPerPage: 15);
}

<style>
    .webGrid {
        width: 100%;
        padding: 10px;
        background-color: ghostwhite;
    }

    .rows {
        background-color: whitesmoke;
    }

    .header {
        background-color: darkgray;
    }

    .select {
        background-color: grey;
    }
</style>

@newGrid.GetHtml(tableStyle: "webGrid", headerStyle: "header", selectedRowStyle:
         "select", rowStyle: "rows", fillEmptyRows: true, columns: newGrid.Columns(newGrid.Column("firstName", "First Name"),
         newGrid.Column("lastName", "Last Name"),
         newGrid.Column("address", "Address"),
         newGrid.Column("city", "City"),
         newGrid.Column("State", "State"),
         newGrid.Column("zip", "Zip"),
         newGrid.Column(header: "Details", format:
                @<text>
                    @Html.ActionLink("Details", "NumbersView", "Phone", new { ID = item.ID, firstName = item.firstName }, null)
                </text> ),

    newGrid.Column(header: "Actions", format:
                                @<text>
                                    <button class="btn btn-info">@Html.ActionLink("Edit", "EditContact", "Phone", new { ID = item.ID }, null)</button>&nbsp;<button class="btn btn-danger">@Html.ActionLink("Delete", "DeleteContact", "Phone", new { ID = item.ID }, null)</button>
                                </text>)))